#!/bin/bash
//this script starts and stops all workloads
status=$2
namespace=$1
deployments=($(kubectl get deployment -n $namespace | awk '{print $1}'))
if [[ $status = stop ]];then

for deployment in "${deployments[@]}"
do
kubectl scale --replicas=0 deployment/$deployment
done

elif [[ $status = start ]];then

for deployment in "${deployments[@]}"
do
kubectl scale --replicas=1 deployment/$deployment
done

else

echo "Please give start or stop command."

fi
