#!/bin/bash
#this script starts and stops all workloads
status=$2
namespace=$1
cronjobs=($(kubectl get cj -n $namespace | grep -v NAME | awk '{print $1}'))
if [[ $status = stop ]];then

 kubectl scale deploy -n boydak-dev --replicas=0 --all

for cronjob in "${cronjobs[@]}"
do
kubectl patch cronjobs -n $namespace $cronjob -p '{"spec" : {"suspend" : true }}'
done

elif [[ $status = start ]];then

 kubectl scale deploy -n boydak-dev --replicas=1 --all

for cronjob in "${cronjobs[@]}"
do
kubectl patch cronjobs -n $namespace $cronjob -p '{"spec" : {"suspend" : false }}'
done

else

echo "Please give start or stop command."

fi
